################################################################################
# Automatically-generated file. Do not edit!
################################################################################

S79_SRCS := 
OBJ_SRCS := 
S_SRCS := 
ASM_SRCS := 
C_SRCS := 
S79_UPPER_SRCS := 
S_UPPER_SRCS := 
O_SRCS := 
EXECUTABLES := 
OBJS := 
C_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
. \
autogen \
simplicity_sdk_2024.12.2/app/common/util/app_button_press \
simplicity_sdk_2024.12.2/app/common/util/app_log \
simplicity_sdk_2024.12.2/app/common/util/app_queue \
simplicity_sdk_2024.12.2/app/common/util/app_rta/src/rtos \
simplicity_sdk_2024.12.2/hardware/board/src \
simplicity_sdk_2024.12.2/hardware/driver/configuration_over_swo/src \
simplicity_sdk_2024.12.2/hardware/driver/mx25_flash_shutdown/src/sl_mx25_flash_shutdown_eusart \
simplicity_sdk_2024.12.2/platform/CMSIS/RTOS2/Source \
simplicity_sdk_2024.12.2/platform/Device/SiliconLabs/EFR32ZG23/Source \
simplicity_sdk_2024.12.2/platform/bootloader/api \
simplicity_sdk_2024.12.2/platform/bootloader/app_properties \
simplicity_sdk_2024.12.2/platform/bootloader/core/flash \
simplicity_sdk_2024.12.2/platform/common/src \
simplicity_sdk_2024.12.2/platform/common/toolchain/src \
simplicity_sdk_2024.12.2/platform/driver/button/src \
simplicity_sdk_2024.12.2/platform/driver/debug/src \
simplicity_sdk_2024.12.2/platform/driver/gpio/src \
simplicity_sdk_2024.12.2/platform/driver/leddrv/src \
simplicity_sdk_2024.12.2/platform/driver/pwm/src \
simplicity_sdk_2024.12.2/platform/emdrv/dmadrv/src \
simplicity_sdk_2024.12.2/platform/emdrv/gpiointerrupt/src \
simplicity_sdk_2024.12.2/platform/emdrv/nvm3/src \
simplicity_sdk_2024.12.2/platform/emlib/src \
simplicity_sdk_2024.12.2/platform/peripheral/src \
simplicity_sdk_2024.12.2/platform/radio/rail_lib/plugin/pa-conversions \
simplicity_sdk_2024.12.2/platform/radio/rail_lib/plugin/rail_util_power_manager_init \
simplicity_sdk_2024.12.2/platform/security/sl_component/se_manager/src \
simplicity_sdk_2024.12.2/platform/security/sl_component/sl_mbedtls_support/src \
simplicity_sdk_2024.12.2/platform/security/sl_component/sl_psa_driver/src \
simplicity_sdk_2024.12.2/platform/security/sl_component/sli_psec_osal/src \
simplicity_sdk_2024.12.2/platform/service/cli/src \
simplicity_sdk_2024.12.2/platform/service/clock_manager/src \
simplicity_sdk_2024.12.2/platform/service/device_init/src \
simplicity_sdk_2024.12.2/platform/service/device_manager/clocks \
simplicity_sdk_2024.12.2/platform/service/device_manager/devices \
simplicity_sdk_2024.12.2/platform/service/device_manager/src \
simplicity_sdk_2024.12.2/platform/service/hfxo_manager/src \
simplicity_sdk_2024.12.2/platform/service/interrupt_manager/src \
simplicity_sdk_2024.12.2/platform/service/iostream/src \
simplicity_sdk_2024.12.2/platform/service/memory_manager/src \
simplicity_sdk_2024.12.2/platform/service/mpu/src \
simplicity_sdk_2024.12.2/platform/service/power_manager/src/common \
simplicity_sdk_2024.12.2/platform/service/power_manager/src/sleep_loop \
simplicity_sdk_2024.12.2/platform/service/sleeptimer/src \
simplicity_sdk_2024.12.2/platform/service/system/src \
simplicity_sdk_2024.12.2/platform/service/udelay/src \
simplicity_sdk_2024.12.2/protocol/z-wave/ZAF/ApplicationUtilities/Actuator \
simplicity_sdk_2024.12.2/protocol/z-wave/ZAF/ApplicationUtilities/AppName \
simplicity_sdk_2024.12.2/protocol/z-wave/ZAF/ApplicationUtilities \
simplicity_sdk_2024.12.2/protocol/z-wave/ZAF/ApplicationUtilities/CCListGenerator \
simplicity_sdk_2024.12.2/protocol/z-wave/ZAF/ApplicationUtilities/EventHandling \
simplicity_sdk_2024.12.2/protocol/z-wave/ZAF/ApplicationUtilities/TrueStatusEngine \
simplicity_sdk_2024.12.2/protocol/z-wave/ZAF/ApplicationUtilities/_commonIF \
simplicity_sdk_2024.12.2/protocol/z-wave/ZAF/ApplicationUtilities/nvm \
simplicity_sdk_2024.12.2/protocol/z-wave/ZAF/CommandClasses/Association/src \
simplicity_sdk_2024.12.2/protocol/z-wave/ZAF/CommandClasses/Basic/src \
simplicity_sdk_2024.12.2/protocol/z-wave/ZAF/CommandClasses/ColorSwitch/src \
simplicity_sdk_2024.12.2/protocol/z-wave/ZAF/CommandClasses/Common \
simplicity_sdk_2024.12.2/protocol/z-wave/ZAF/CommandClasses/DeviceResetLocally \
simplicity_sdk_2024.12.2/protocol/z-wave/ZAF/CommandClasses/FirmwareUpdate/src \
simplicity_sdk_2024.12.2/protocol/z-wave/ZAF/CommandClasses/Indicator/src \
simplicity_sdk_2024.12.2/protocol/z-wave/ZAF/CommandClasses/ManufacturerSpecific \
simplicity_sdk_2024.12.2/protocol/z-wave/ZAF/CommandClasses/MultiChan/src \
simplicity_sdk_2024.12.2/protocol/z-wave/ZAF/CommandClasses/MultilevelSwitch/src \
simplicity_sdk_2024.12.2/protocol/z-wave/ZAF/CommandClasses/PowerLevel \
simplicity_sdk_2024.12.2/protocol/z-wave/ZAF/CommandClasses/Security \
simplicity_sdk_2024.12.2/protocol/z-wave/ZAF/CommandClasses/Supervision/src \
simplicity_sdk_2024.12.2/protocol/z-wave/ZAF/CommandClasses/Version \
simplicity_sdk_2024.12.2/protocol/z-wave/ZAF/CommandClasses/ZWavePlusInfo/src \
simplicity_sdk_2024.12.2/protocol/z-wave/ZAF/ProtocolConfig/src \
simplicity_sdk_2024.12.2/protocol/z-wave/ZAF/TransportLayer/src \
simplicity_sdk_2024.12.2/protocol/z-wave/ZAF/configuration/src \
simplicity_sdk_2024.12.2/protocol/z-wave/platform/SiliconLabs/AppsHw/src/common \
simplicity_sdk_2024.12.2/protocol/z-wave/platform/SiliconLabs/components/zw_cli_common \
simplicity_sdk_2024.12.2/util/third_party/freertos/cmsis/Source \
simplicity_sdk_2024.12.2/util/third_party/freertos/kernel \
simplicity_sdk_2024.12.2/util/third_party/freertos/kernel/portable/GCC/ARM_CM33_NTZ/non_secure \
simplicity_sdk_2024.12.2/util/third_party/freertos/kernel/portable/MemMang \
simplicity_sdk_2024.12.2/util/third_party/freertos/kernel/portable/SiliconLabs \
simplicity_sdk_2024.12.2/util/third_party/mbedtls/library \
simplicity_sdk_2024.12.2/util/third_party/printf \
simplicity_sdk_2024.12.2/util/third_party/printf/src \

